- name: Create Required Directories
  file: 
    path: "{{item}}"
    state: directory
    owner: "{{beat_user}}"
    group: "{{beat_group}}"
  with_items:
     - "{{ log_dir }}"
     - "{{ data_dir }}"
     - "{{ conf_dir }}"

- when: beat_config is defined
  name: Configure beat
  template:
    src: "beatTemplate.yml.j2"
    dest: "{{ conf_dir }}/{{ beat_cfg_file }}"
    owner: "{{beat_user}}"
    group: "{{beat_group}}"
    mode: 0644
    force: yes
  notify: restart beat

- when: use_system_d
  block:
    - name: Copy Systemd File for Instance
      template: 
        src: systemd/beat.service.j2
        dest: "{{instance_sysd_script}}"
        mode: 0644
        force: yes
      notify: 
        - reload systemd configuration
        - restart beat

# TODO; Add support for non-systemd          
# -when: not use_system_d
#  block: 

- name: Delete Default Beat config File
  file: 
    dest: "{{ beat_path_conf }}/{{ beat_cfg_file }}" 
    state: absent

- name: Delete Default Sysconfig File
  file: 
    dest: "{{ sysd_script }}" 
    state: absent
