---
- name: Add Elastic repo public signing key
  shell: rpm --import {{ beats_gpgkey }}
  tags: 
     - install

- name: Add Beats repo
  copy: src=beats.repo dest=/etc/yum.repos.d/ mode=0644
  tags: 
     - install

- name: Install Beat
  yum:
    name: "{{ beat_name }}{% if beat_version is defined %}-{{beat_version}}{% endif %}"
    update_cache: yes
    state: present
  tags: 
     - install

