---
# tasks file for ansible-beats
- include: check.yaml
  tags:
    - check

- when: beat.service_state is defined
  block:
    - name: "Update service state: {{beat.service_state}}"
      service:
        name: "{{ beat.name }}"
        state: "{{ beat.service_state }}"
  tags:
    - service


- when: beat.service_enabled is defined
  block:
    - name: Enable beat at boot
      service:
        name: "{{ beat.name }}"
        enabled: "{{ beat.service_enabled }}"
  tags:
    - service

- when: beat.install
  block:
    - include: Ubuntu.yaml
      when: ansible_distribution == 'Ubuntu'
    - include: CentOS.yaml
      when: ansible_distribution == "CentOS"
  tags:
    - install
       
- when: beat.config is defined
  block:
    - debug: var=beat.config             

    - name: Configure beat
      template:
          src: "beatTemplate.yml.j2"
          dest: "/etc/{{ beat.name }}/{{ beat.config_file }}"
      notify: restart beat
  tags: 
     - config
    

