---
# tasks file for ansible-beats
- include: check.yaml
  tags:
    - check

- name: check-set-parameters
  include: beats-parameters.yml
  tags:
    - always

- when: beat_svc_state is defined
  block:
    - name: "Update service state: {{beat_svc_state}}"
      service:
        name: "{{ beat_type }}"
        state: "{{ beat_svc_state }}"
  tags:
    - service


- when: beat_svc_enabled is defined
  block:
    - name: Enable beat at boot
      service:
        name: "{{ beat_type }}"
        enabled: "{{ beat_svc_enabled }}"
  tags:
    - service

# Control installation with `beat_install` var, or `install` tag.
- when: beat_install
  block:
    - include: beats-Ubuntu.yaml
      when: ansible_distribution == 'Ubuntu'
    - include: beats-CentOS.yaml
      when: ansible_distribution == "CentOS"
  tags:
    - install

- include: beats-config.yml      
  tags: 
     - config
       
- meta: flush_handlers
    

