---
# tasks file for ansible-beats
- include: check.yaml
  tags:
    - check

- when: beat_svc_state is defined
  block:
    - name: "Update service state: {{beat_svc_state}}"
      service:
        name: "{{ beat_type }}"
        state: "{{ beat_svc_state }}"
  tags:
    - service


- when: beat_svc_enabled is defined
  block:
    - name: Enable beat at boot
      service:
        name: "{{ beat_type }}"
        enabled: "{{ beat_svc_enabled }}"
  tags:
    - service

- when: beat_install
  block:
    - include: Ubuntu.yaml
      when: ansible_distribution == 'Ubuntu'
    - include: CentOS.yaml
      when: ansible_distribution == "CentOS"
  tags:
    - install

- include: beats-config.yml      
  tags: 
     - config
       
    

