---
- name: Add Elastic repo public signing key
  apt_key: "url={{beat_gpgkey}} state=present"
  tags: 
     - install

- stat: path=/etc/apt/sources.list.d/beats.list
  register: repo_st
- name: Add Beats repo
  when: repo_st.stat.exists is defined and not repo_st.stat.exists
  shell: echo "deb https://packages.elastic.co/beats/apt stable main" |  tee -a /etc/apt/sources.list.d/beats.list 
  tags: 
     - install

- name: Install beat
  apt: 
    name: "{{ beat_name }}{% if beat_version is defined %}={{ beat_version }}{% endif %}"
    update_cache: yes
    state: present
  tags: 
     - install


