FROM ubuntu:16.04
RUN apt-get update

# Install Ansible
RUN apt-get install -y software-properties-common git libyaml-dev libpython2.7-dev python-setuptools apt-transport-https
#RUN apt-add-repository -y ppa:ansible/ansible
RUN apt-get update
#RUN apt-get install -y ansible
RUN apt-get install -y python-pip
RUN pip install ansible

# Install Ansible inventory file
RUN if [ ! -d "/etc/ansible" ]; then mkdir /etc/ansible; fi
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
